### ISSUE TITLE
Rsiz value is not consistent with ISO/IEC 15444-15

### ISSUE THREAD

**Issue by bitsgalore** [osamu620/OpenHTJ2K#148]
If I use OpenHTJ2K to create either a JPH file or a codestream, opening these files in a Hex editor shows that they have the following Rsiz value:

```
40 00
```

However, Annex A (HTJ2K codestream syntax) of [ISO/IEC 15444-15:2019 (E)](https://www.itu.int/rec/dologin_pub.asp?lang=e&id=T-REC-T.814-201906-I!!PDF-E&type=items) says that the 14th bit of Rsiz shall be 1 for HTJ2K codestreams:

> ## A.2 SIZ marker segment
> Bit 14 of Rsiz shall be equal to 1.

Since the actual value is 0 OpenHTJ2K-produced files, it looks like the software isn't quite following the standard here.

**Comment by osamu620** [comment]
Hi @bitsgalore, Thanks for raising this issue. Let me explain how Rsiz works with JPEG 2000 Part 15.

To use JPEG 2000 Part 15, a.k.a. HTJ2K, the CAP marker shall be signaled to tell decoders the capability HTJ2K features is required to decode this codestream.

The definition of Rsiz is in the spec of ISO/IEC 15444-1: 2019. Table A.10 in the spec, you can see the note at the bottom;

NOTE 1 – The two MSBs of Rsiz are used as follows:
- 10 – Rec. ITU-T T.801 | ISO/IEC 15444-2 capabilities
- 01 – Extended capabilities, as identified by a CAP marker segment, not including capabilities specified in Rec. ITU-T T.801 | ISO/IEC 15444-2
- 11 – Rec.   capabilities extended via a CAP marker segment

Actually, ISO/IEC 15444-1:2019 does not specify the permitted values of the Rsiz parameter when the two MSBs are set to 0b01. This is a defect of the spec. So JPEG committee will replace the second bullet of Table A.10, Note 1
with a statement that:
- **when the two MSBs are set to 0b01 and all other bits are zero**, the capabilities are signaled in CAP alone and not otherwise constrained.
- all other values are reserved.

Rsiz is 16-bit wide bit-field. According to the revised NOTE 1, the Rsiz value should be 
```
MSB(15) 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0
0b    0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0 = 0x40 00
```

The revised explanation in the spec will be available in the ISO/IEC 15444-1 5th edition which is now under development.

**Comment by aous72** [comment]
Perhaps, I can chip in.
JPEG2000 employs big-endian everywhere -- not sure if other standards do that.  
That is why the bytes have this order.

Cheers,
Aous.
