### ISSUE TITLE
conformance test failures

### ISSUE THREAD

**Issue by boxerab** [osamu620/OpenHTJ2K#38]
Checking the test log, I see that tests 191,192, 121 and 122 are failing.
@osamu620 are you able to share what the issue is for these tests ? 
Thanks!

**Comment by osamu620** [comment]
@boxerab 
OpenHTJ2K has passed those test cases for PAE (Peak Absolute Error). For MSE, has not passed for a component (component #01) with a slightly large MSE. Kakadu v8.10 produces similar results, too. So, I have marked the cases to be failing.

Another way to make things right is to relax the threshold for MSE. I suspect the threshold values for MSE written in 15444-4 spec are too tight for the test cases because the same observations come with Kakadu.

How do you think?

**Comment by boxerab** [comment]
@osamu620 thanks, I like your approach of marking the cases as failing. Is it possible to give feedback to the JPEG committee about these MSE values ? If even the reference software fails, the numbers should be changed.

**Comment by osamu620** [comment]
@boxerab 
I think it is possible. I will contact the JPEG committee members and tell them the current situation. The next JPEG meeting is scheduled from October 18 - 22.

**Comment by boxerab** [comment]
@osamu620 thank you  - it would be great if you could let them know.

**Comment by boxerab** [comment]
closing
